import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "swiper/css";

import LayoutWrapper from "@/components/modules/LayoutWrapper/layoutWrapper";

export const metadata = {
  title: "meli-maharat-source-hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <LayoutWrapper>{children}</LayoutWrapper>
        <ToastContainer rtl={true} autoClose={4000} theme="colored" />
      </body>
    </html>
  );
}
